os:
  - linux

language: cpp

compiler:
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main' -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cmake binutils-dev libedit-dev libtbb-dev libstdc++-4.9-dev llvm-3.6 llvm-3.6-dev clang-3.6

before_script:
  - export CXX="clang++-3.6" 
  - export CC="clang-3.6"
  - git clone https://github.com/zeux/pugixml
  - cd pugixml
  - git checkout v1.6
  - clang++ src/pugixml.cpp -g -MMD -MP -fPIC -shared -o libpugixml.so
  - sudo cp libpugixml.so /usr/lib/
  - sudo cp src/pugixml.hpp src/pugiconfig.hpp /usr/include/
  - cd ..
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=Release
  - make

script:
   - echo "build passed"

notifications:
  email:
    on_success: always
    on_failure: always