os:
  - linux

language: cpp

compiler:
  - clang

before_install:
  - echo "yes" | lsb_release -a
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main' -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cmake libiberty-dev libpugixml-dev libedit-dev libtbb-dev libstdc++-4.9-dev llvm-3.6 llvm-3.6-dev clang-3.6

before_script:
  - mkdir build
  - cd build
  - export CXX="clang++-3.6" CC="clang-3.6"; cmake ../ -DCMAKE_BUILD_TYPE=Release

script:
   - echo "passed"

notifications:
  email:
    on_success: always
    on_failure: always